language: generic
sudo: required
dist: trusty
osx_image: xcode11

# Environment
env:
  global:
    - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-08-26-a

# Build Matrix
matrix:
  include:
    - os: osx
    - os: linux
    - os: linux # ARM linux
      env: CROSS_COMPILE=1 ARM_ARCH_DIR=arm-linux-gnueabi
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qemu
            - qemu-system-arm
    - os: linux # AArch64 Linux
      env: CROSS_COMPILE=1 ARM_ARCH_DIR=aarch64-linux-gnu
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qemu
            - qemu-system-arm

# Allow script execution
before_install:
  - chmod +x .travis/deps.sh
  - chmod +x .travis/build.sh
  - chmod +x .travis/notify.sh

# Install dependencies & build
install: ./.travis/deps.sh
script: ./.travis/build.sh

# Notify build status
after_success: ./notify.sh success $WEBHOOK_URL # Success
after_failure: ./notify.sh failure $WEBHOOK_URL # Failure