language: generic
sudo: required
dist: trusty
osx_image: xcode11

# Environment
env:
  global:
    - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-08-26-a

# Build Matrix
matrix:
  include:
    - os: osx
    - os: linux
      env: COMPILER=clang CLANG=6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0

# Allow script execution
before_install:
  - chmod +x .travis/deps.sh
  - chmod +x .travis/build.sh
  - chmod +x .travis/notify.sh

# Install dependencies & build
install: ./.travis/deps.sh
script: ./.travis/build.sh

# Notify build status
after_success: ./notify.sh success $WEBHOOK_URL # Success
after_failure: ./notify.sh failure $WEBHOOK_URL # Failure