language: swift
sudo: required

# Environment
env:
  global:
    - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-08-26-a

# Build Matrix
matrix:
  allow_failures:
    - os: linux # Debug builds error in SIL (release works though...)
  include:
    - os: osx # macOS 10.14 / x86
      osx_image: xcode11
    - os: linux # ubuntu 14.04 / x86
      dist: trusty
    - os: linux # ubuntu 16.04 / x86
      dist: xenial
    - os: linux # ubuntu 18.04 / x86
      dist: bionic
    #- os: linux # ARM linux
    #  env: CROSS_COMPILE=1 ARM_ARCH_DIR=arm-linux-gnueabi
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - qemu
    #        - qemu-system-arm
    #- os: linux # AArch64 Linux
    #  env: CROSS_COMPILE=1 ARM_ARCH_DIR=aarch64-linux-gnu
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - qemu
    #        - qemu-system-arm

# Allow script execution
before_install:
  - chmod +x .travis/deps.sh
  - chmod +x .travis/build.sh
  - chmod +x .travis/notify.sh

# Install Dependencies
install: ./.travis/deps.sh

# Build
script: ./.travis/build.sh

# Notify status
after_success: ./notify.sh success $WEBHOOK_URL # Success
after_failure: ./notify.sh failure $WEBHOOK_URL # Failure