language: generic
sudo: required
dist: trusty
osx_image: xcode11

# Build Matrix
matrix:
  include:
    - os: osx
    - os: linux
      env:
        - COMPILER=clang CLANG=9.0
        - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-08-26-a
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-9.0
          packages:
            - clang-9.0

# Dependencies
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    fi

# Build Phase
script:
  - swift build
  - swift build -c release
  - swift test

# Success Notifier
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
# Failure Notifier
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL